In [108]:
import pandas as pd

df = pd.read_excel("containers_pool.xlsx")

In [109]:
df_voy=df[['shipping_line','voyage_id']]
print(df_voy)

    shipping_line        voyage_id
0         CMA CGM  CMA-20251129-01
1         CMA CGM  CMA-20251129-01
2         CMA CGM  CMA-20251129-01
3         CMA CGM  CMA-20251129-01
4         CMA CGM  CMA-20251129-01
..            ...              ...
595           MSC  MSC-20251212-02
596           MSC  MSC-20251212-02
597           MSC  MSC-20251212-02
598           MSC  MSC-20251212-02
599           MSC  MSC-20251212-02

[600 rows x 2 columns]

In [110]:
%%sql
select avg(poids_kg) from df

   avg(poids_kg)
0      18157.325

In [111]:
z=df.loc[0:3 ,"shipping_line"]
print(z)

0    CMA CGM
1    CMA CGM
2    CMA CGM
3    CMA CGM
Name: shipping_line, dtype: object

In [112]:
z=df.loc[2]
print(z)

container_id                C1000210
type                       DANGEROUS
shipping_line                CMA CGM
voyage_id            CMA-20251129-01
import_export                 IMPORT
size_ft                           40
plein                              1
poids_kg                       21166
date_arrivee     2025-11-03 11:00:00
date_depart      2025-11-29 01:45:00
Name: 2, dtype: object

In [113]:

y=df.iloc[2]
print(y)

container_id                C1000210
type                       DANGEROUS
shipping_line                CMA CGM
voyage_id            CMA-20251129-01
import_export                 IMPORT
size_ft                           40
plein                              1
poids_kg                       21166
date_arrivee     2025-11-03 11:00:00
date_depart      2025-11-29 01:45:00
Name: 2, dtype: object

In [114]:
unique_dates=df['date_arrivee'].unique()
print(unique_dates)

<DatetimeArray>
['2025-11-03 11:00:00', '2025-11-05 00:00:00', '2025-11-13 14:45:00',
 '2025-11-22 03:00:00', '2025-11-09 01:00:00', '2025-11-19 10:00:00',
 '2025-11-27 14:45:00', '2025-11-27 20:15:00', '2025-11-30 11:15:00',
 '2025-12-25 22:15:00', '2025-12-26 18:15:00', '2026-01-12 08:45:00',
 '2025-12-31 08:00:00', '2025-12-31 22:45:00', '2026-01-10 11:30:00',
 '2026-01-17 14:30:00', '2025-12-24 23:45:00', '2026-01-13 01:15:00',
 '2026-01-19 16:15:00', '2026-01-13 11:30:00', '2026-01-18 21:30:00',
 '2026-01-25 09:45:00', '2026-01-12 14:00:00', '2026-01-27 04:00:00',
 '2026-01-29 15:00:00', '2025-11-01 21:45:00', '2025-11-05 08:45:00',
 '2025-11-07 02:30:00', '2025-11-27 18:30:00', '2025-11-21 14:00:00',
 '2025-11-21 15:15:00', '2025-12-01 19:00:00', '2025-12-08 01:00:00',
 '2025-12-02 22:45:00', '2025-12-05 15:00:00', '2025-12-05 21:00:00',
 '2025-12-19 16:45:00', '2025-12-25 15:15:00', '2025-12-30 05:00:00',
 '2026-01-01 21:15:00', '2026-01-14 03:15:00', '2025-12-26 02:30:00',
 '2025-12-30 14:15:00', '2026-01-07 07:30:00', '2026-01-09 16:30:00',
 '2025-11-16 00:00:00', '2025-12-08 20:45:00', '2025-12-11 12:30:00',
 '2025-12-26 00:00:00', '2025-12-28 05:30:00', '2025-12-28 15:45:00',
 '2025-12-10 02:30:00', '2025-12-22 02:30:00', '2025-12-29 17:15:00',
 '2025-12-22 13:00:00', '2025-12-27 10:45:00', '2025-12-29 13:15:00',
 '2026-01-02 16:45:00', '2025-12-30 13:30:00', '2026-01-08 19:45:00',
 '2026-01-23 05:45:00', '2026-01-17 12:30:00', '2026-01-26 16:00:00',
 '2026-01-11 17:45:00', '2026-01-20 13:45:00', '2026-01-29 00:00:00',
 '2026-01-30 07:30:00', '2025-12-20 10:30:00', '2025-12-24 02:45:00',
 '2025-12-27 21:15:00', '2026-01-26 05:30:00', '2026-01-28 09:00:00',
 '2026-01-28 23:45:00', '2025-11-04 03:15:00', '2025-11-10 03:45:00',
 '2025-11-25 23:00:00', '2025-11-29 00:30:00', '2025-12-09 01:30:00',
 '2025-12-20 07:00:00', '2025-12-21 16:00:00', '2025-12-27 07:45:00',
 '2025-12-29 12:45:00', '2026-01-01 01:30:00', '2026-01-02 00:30:00',
 '2025-12-30 13:45:00', '2025-12-31 19:00:00', '2026-01-07 17:15:00',
 '2026-01-07 17:30:00', '2025-11-19 04:30:00', '2025-11-26 09:30:00',
 '2025-11-29 01:00:00', '2025-12-01 02:15:00', '2025-12-06 20:15:00']
Length: 93, dtype: datetime64[ns]

In [115]:
%%sql
select * from df where poids_kg < 5000

,container_id,type,shipping_line,voyage_id,import_export,size_ft,plein,poids_kg,date_arrivee,date_depart
0,C00273,EMPTY,CMA CGM,CMA-20260118-01,EXPORT,40,0,3800,2026-01-12 08:45:00,2026-01-18 05:15:00
1,C1000386,EMPTY,CMA CGM,CMA-20260118-01,EXPORT,40,0,3800,2026-01-12 08:45:00,2026-01-18 05:15:00
2,C1000388,EMPTY,CMA CGM,CMA-20260118-01,EXPORT,40,0,3800,2026-01-12 08:45:00,2026-01-18 05:15:00
3,C1000389,EMPTY,CMA CGM,CMA-20260118-01,EXPORT,40,0,3800,2026-01-12 08:45:00,2026-01-18 05:15:00
4,C1000392,EMPTY,CMA CGM,CMA-20260118-01,EXPORT,40,0,3800,2026-01-12 08:45:00,2026-01-18 05:15:00
...,...,...,...,...,...,...,...,...,...,...
110,C1000534,EMPTY,MSC,MSC-20251212-02,EXPORT,40,0,3800,2025-12-06 20:15:00,2025-12-12 01:45:00
111,C1000536,EMPTY,MSC,MSC-20251212-02,EXPORT,40,0,3800,2025-12-06 20:15:00,2025-12-12 01:45:00
112,C1000537,EMPTY,MSC,MSC-20251212-02,EXPORT,40,0,3800,2025-12-06 20:15:00,2025-12-12 01:45:00
113,C1000542,EMPTY,MSC,MSC-20251212-02,EXPORT,40,0,3800,2025-12-06 20:15:00,2025-12-12 01:45:00
114,C1000545,EMPTY,MSC,MSC-20251212-02,EXPORT,40,0,3800,2025-12-06 20:15:00,2025-12-12 01:45:00

In [116]:
%%sql
select * from df where poids_kg > 20000

,container_id,type,shipping_line,voyage_id,import_export,size_ft,plein,poids_kg,date_arrivee,date_depart
0,C00151,DANGEROUS,CMA CGM,CMA-20251129-01,IMPORT,40,1,21166,2025-11-03 11:00:00,2025-11-29 01:45:00
1,C1000206,DANGEROUS,CMA CGM,CMA-20251129-01,IMPORT,40,1,21166,2025-11-03 11:00:00,2025-11-29 01:45:00
2,C1000210,DANGEROUS,CMA CGM,CMA-20251129-01,IMPORT,40,1,21166,2025-11-03 11:00:00,2025-11-29 01:45:00
3,C1000211,DANGEROUS,CMA CGM,CMA-20251129-01,IMPORT,40,1,21166,2025-11-03 11:00:00,2025-11-29 01:45:00
4,C1000219,DANGEROUS,CMA CGM,CMA-20251129-01,IMPORT,40,1,21166,2025-11-03 11:00:00,2025-11-29 01:45:00
...,...,...,...,...,...,...,...,...,...,...
280,C1000558,DRY,MAERSK,MAE-20260115-02,EXPORT,40,1,26981,2025-12-30 13:45:00,2026-01-15 22:30:00
281,C1000559,DRY,MAERSK,MAE-20260115-02,EXPORT,40,1,26981,2025-12-30 13:45:00,2026-01-15 22:30:00
282,C1000567,DRY,MAERSK,MAE-20260115-02,EXPORT,40,1,26981,2025-12-30 13:45:00,2026-01-15 22:30:00
283,C00299,DRY,MSC,MSC-20251212-01,EXPORT,40,1,29504,2025-11-19 04:30:00,2025-12-12 01:45:00
284,C1000528,DRY,MSC,MSC-20251212-02,EXPORT,40,1,29504,2025-11-19 04:30:00,2025-12-12 01:45:00

In [117]:
df_light=df[df['poids_kg']<5000]
print(df_light)

    container_id   type shipping_line        voyage_id import_export  size_ft  \
90        C00273  EMPTY       CMA CGM  CMA-20260118-01        EXPORT       40
91      C1000386  EMPTY       CMA CGM  CMA-20260118-01        EXPORT       40
92      C1000388  EMPTY       CMA CGM  CMA-20260118-01        EXPORT       40
93      C1000389  EMPTY       CMA CGM  CMA-20260118-01        EXPORT       40
94      C1000392  EMPTY       CMA CGM  CMA-20260118-01        EXPORT       40
..           ...    ...           ...              ...           ...      ...
595     C1000534  EMPTY           MSC  MSC-20251212-02        EXPORT       40
596     C1000536  EMPTY           MSC  MSC-20251212-02        EXPORT       40
597     C1000537  EMPTY           MSC  MSC-20251212-02        EXPORT       40
598     C1000542  EMPTY           MSC  MSC-20251212-02        EXPORT       40
599     C1000545  EMPTY           MSC  MSC-20251212-02        EXPORT       40

     plein  poids_kg        date_arrivee         date_depart
90       0      3800 2026-01-12 08:45:00 2026-01-18 05:15:00
91       0      3800 2026-01-12 08:45:00 2026-01-18 05:15:00
92       0      3800 2026-01-12 08:45:00 2026-01-18 05:15:00
93       0      3800 2026-01-12 08:45:00 2026-01-18 05:15:00
94       0      3800 2026-01-12 08:45:00 2026-01-18 05:15:00
..     ...       ...                 ...                 ...
595      0      3800 2025-12-06 20:15:00 2025-12-12 01:45:00
596      0      3800 2025-12-06 20:15:00 2025-12-12 01:45:00
597      0      3800 2025-12-06 20:15:00 2025-12-12 01:45:00
598      0      3800 2025-12-06 20:15:00 2025-12-12 01:45:00
599      0      3800 2025-12-06 20:15:00 2025-12-12 01:45:00

[115 rows x 10 columns]

In [118]:
shape=df.shape
print(shape)

(600, 10)